# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-28 06:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('misago_threads', '0009_auto_20180326_0010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='original',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='parsed',
            field=models.TextField(blank=True, null=True),
        ),
    ]
