# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-29 06:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('misago_threads', '0011_auto_20180529_0605'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='original',
            field=models.TextField(blank=True, null=True),
        ),
    ]
