# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-29 06:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('misago_threads', '0012_auto_20180529_0605'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_name', models.CharField(max_length=64)),
                ('created_on', models.DateTimeField(db_index=True)),
                ('updated_on', models.DateTimeField()),
                ('search_document', models.TextField(blank=True, null=True)),
                ('thread', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='misago_threads.Thread')),
            ],
        ),
        migrations.AddIndex(
            model_name='tag',
            index=models.Index(fields=['tag_name'], name='misago_thre_tag_nam_95b94c_idx'),
        ),
    ]
