# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-04 14:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('misago_threads', '0013_auto_20180529_0608'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_type', models.CharField(max_length=64)),
                ('reporter_id', models.PositiveIntegerField()),
                ('created_on', models.DateTimeField(db_index=True)),
                ('updated_on', models.DateTimeField()),
            ],
        ),
        migrations.AddIndex(
            model_name='report',
            index=models.Index(fields=['report_type'], name='misago_thre_report__3013f5_idx'),
        ),
    ]
