# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-04 14:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('misago_threads', '0014_auto_20180604_1417'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='record_id',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
