# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-29 12:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('misago_users', '0011_auto_20180331_2208'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='tags',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
